// Dados estáticos de fallback — usados quando Appwrite não estiver configurado
// ou durante o build estático

export const STATIC_TREATMENTS = [
  {
    $id: '1',
    order: 1,
    icon: '01',
    title: 'Varizes',
    subtitle: 'Tratamento cirúrgico e minimamente invasivo',
    description: 'Diagnóstico preciso e tratamento cirúrgico ou minimamente invasivo das varizes dos membros inferiores, combinando funcionalidade e estética com tecnologia de ponta.',
    duration: '2–3 horas',
    recovery: '7–14 dias',
    active: true,
    highlight: true,
  },
  {
    $id: '2',
    order: 2,
    icon: '02',
    title: 'Laser Avançado',
    subtitle: 'Tecnologia transdérmica',
    description: 'Técnica não cirúrgica que utiliza laser de alta precisão para remover vasinhos e pequenas varizes com mínimo desconforto e rápida recuperação.',
    duration: '30–60 min',
    recovery: '1–3 dias',
    active: true,
    highlight: false,
  },
  {
    $id: '3',
    order: 3,
    icon: '03',
    title: 'Escleroterapia',
    subtitle: 'Eliminação de vasinhos',
    description: 'Procedimento minimamente invasivo realizado em consultório para eliminar vasinhos e pequenas varizes com excelentes resultados estéticos comprovados.',
    duration: '30–45 min',
    recovery: '2–5 dias',
    active: true,
    highlight: false,
  },
  {
    $id: '4',
    order: 4,
    icon: '04',
    title: 'Ecografia Vascular',
    subtitle: 'Diagnóstico por imagem',
    description: 'Exame complementar realizado pela própria especialista, com diagnóstico preciso e personalizado na mesma consulta, sem necessidade de retorno.',
    duration: 'Na consulta',
    recovery: 'Imediato',
    active: true,
    highlight: false,
  },
  {
    $id: '5',
    order: 5,
    icon: '05',
    title: 'Trombose Venosa',
    subtitle: 'Diagnóstico e prevenção',
    description: 'Avaliação, diagnóstico e tratamento da trombose venosa profunda (TVP) e superficial, prevenindo complicações graves como a embolia pulmonar.',
    duration: 'Variável',
    recovery: 'Monitorado',
    active: true,
    highlight: false,
  },
  {
    $id: '6',
    order: 6,
    icon: '06',
    title: 'Insuficiência Venosa',
    subtitle: 'Tratamento completo',
    description: 'Avaliação e tratamento da insuficiência venosa crônica, prevenindo úlceras, inchaços e desconforto nas pernas com abordagem individualizada.',
    duration: 'Variável',
    recovery: 'Contínuo',
    active: true,
    highlight: false,
  },
];

export const STATIC_SURGERIES = [
  {
    $id: '1',
    order: 1,
    number: '01',
    title: 'Safenectomia',
    description: 'Remoção cirúrgica da veia safena doente, indicada para casos graves de insuficiência venosa com varizes volumosas. Procedimento clássico com alta taxa de sucesso e resultados duradouros.',
    duration: '2–3 horas',
    recovery: '7–14 dias',
    anesthesia: 'Raquidiana ou geral',
    active: true,
  },
  {
    $id: '2',
    order: 2,
    number: '02',
    title: 'Ablação a Laser Endovenosa',
    description: 'Técnica minimamente invasiva que utiliza energia laser para obliterar veias insuficientes por dentro, substituindo a safenectomia convencional com menor trauma e recuperação mais rápida.',
    duration: '1–2 horas',
    recovery: '3–7 dias',
    anesthesia: 'Local com sedação',
    active: true,
  },
  {
    $id: '3',
    order: 3,
    number: '03',
    title: 'Microcirurgia de Varizes',
    description: 'Remoção de varizes por microincisões, sem necessidade de sutura. Excelentes resultados estéticos e funcionais com mínimo trauma cirúrgico e cicatriz imperceptível.',
    duration: '1–3 horas',
    recovery: '5–10 dias',
    anesthesia: 'Local ou raquidiana',
    active: true,
  },
  {
    $id: '4',
    order: 4,
    number: '04',
    title: 'Cirurgia Arterial',
    description: 'Procedimentos vasculares para tratamento de doenças arteriais como aneurismas, estenoses e isquemia de membros, com suporte de imagem vascular intraoperatória.',
    duration: 'Variável',
    recovery: '10–21 dias',
    anesthesia: 'Geral ou raquidiana',
    active: true,
  },
];

export const STATIC_POSTS = [
  {
    $id: 'p1',
    slug: 'como-se-livrar-das-varizes',
    title: 'Como se livrar das varizes definitivamente?',
    excerpt: 'O primeiro passo para descobrir qual o melhor tratamento para o seu caso é procurar um médico angiologista e cirurgião vascular especializado.',
    content: '',
    category: 'Tratamentos',
    published_at: '2024-11-10',
    published: true,
    cover_url: 'https://spaziovascolare.com.br/wp-content/uploads/2023/02/fundo-1388026885-1024x1024.jpg',
  },
  {
    $id: 'p2',
    slug: 'sinais-da-trombose-venosa',
    title: 'Como identificar os sinais da trombose venosa?',
    excerpt: 'A trombose venosa profunda (TVP) ocorre quando um coágulo se forma em uma veia profunda impedindo a circulação normal do sangue.',
    content: '',
    category: 'Saúde Vascular',
    published_at: '2024-10-20',
    published: true,
    cover_url: 'https://spaziovascolare.com.br/wp-content/uploads/2023/02/fundo-1388026885-1024x1024.jpg',
  },
  {
    $id: 'p3',
    slug: 'tratamento-de-vasinhos-a-laser',
    title: 'Como é feito o tratamento de vasinhos a laser?',
    excerpt: 'A aplicação de laser para eliminar vasinhos é uma técnica não cirúrgica que tem sido cada vez mais usada para remover marcas indesejadas na pele.',
    content: '',
    category: 'Laser',
    published_at: '2024-09-15',
    published: true,
    cover_url: 'https://spaziovascolare.com.br/wp-content/uploads/2023/02/fundo-1388026885-1024x1024.jpg',
  },
];
